pipeline{
    agent any
    tools{
        nodejs 'nodejs'
    }
    environment {
        SCANNER_HOME=tool 'sonar-server'
    }
    stages {
        stage('Workspace Cleaning'){
            steps{
                cleanWs()
            }
        }
        stage('Checkout from Git'){
            steps{
                git branch: 'main', url: 'https://github.com/GilbertDaniel/netflix-clone-end-to-end-DevSecOps.git'
            }
        }       
    }
    stage('Install Dependencies') {
            steps {
                dir('Application-Code') {
                    // Install project dependencies (needed for OWASP + build)
                    sh 'npm install'
                }
            }
        }
    stage("SonarQube Analysis") {
        steps {
            dir('Application-Code') {
                withSonarQubeEnv('sonar-server') {
                    // Run SonarQube scanner using npx (no global install)
                    sh '''
                    echo "🔍 Starting SonarQube Analysis..."
                    npx @sonar/scan \
                    -Dsonar.projectKey=NetflixClone \
                    -Dsonar.projectName=NetflixClone \
                    -Dsonar.sources=src \
                    -Dsonar.language=ts \
                    -Dsonar.exclusions=dist/**,node_modules/**,public/** \
                    -Dsonar.host.url=$SONAR_HOST_URL \
                    -Dsonar.login=$SONAR_AUTH_TOKEN
                    '''
                }
            }
        }
    }
    post {
        always {
            script {
                def colorCode = currentBuild.result == 'SUCCESS' ? '#2eb886' : 
                                currentBuild.result == 'FAILURE' ? '#ff0000' : '#daa038'
    
                slackSend(
                    channel: '#devops-alerts',
                    color: colorCode,
                    message: """
                    *🚀 Jenkins Build Notification*
                    *Project:* ${env.JOB_NAME}
                    *Build Number:* #${env.BUILD_NUMBER}
                    *Status:* *${currentBuild.result}*
                    *URL:* <${env.BUILD_URL}|Open Build>
    
                    ${currentBuild.result == 'SUCCESS' ? '✅ All steps completed successfully!' : 
                    currentBuild.result == 'FAILURE' ? '❌ Build failed. Please check logs.' : 
                    '⚠️ Build is unstable or aborted.'}
                    """.stripIndent()
                )
            }
        }
    }
}
